import { v4 as uuidv4 } from "uuid";
import { AllProductsType } from "@/app/types";

export const allProducts: AllProductsType[] = [
	{
		id: uuidv4(),
		name: "Knitted Joggers",
		image: "/assets/new-arrival/new-arrival-one.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Full Sleeve",
		image: "/assets/new-arrival/new-arrival-two.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Active T-Shirts",
		image: "/assets/new-arrival/new-arrival-three.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Urban Shirts",
		image: "/assets/new-arrival/new-arrival-four.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Hawaiian Shirts",
		image: "/assets/big-saving-zone/big-saving-zone-one.png",
		gender: "unisex",
		promo: "UP TO 50% OFF",
		desc: "Dress up in summer vibe",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Printed T-Shirts",
		image: "assets/big-saving-zone/big-saving-zone-two.png",
		gender: "unisex",
		promo: "UP TO 40% OFF",
		desc: "New Designs Every Week",
		custom: "limited",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Cargo Joggers",
		image: "/assets/big-saving-zone/big-saving-zone-three.png",
		gender: "unisex",
		promo: "UP TO 50% OFF",
		desc: "Move with style & comfort",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Urban Shirts",
		image: "/assets/big-saving-zone/big-saving-zone-four.png",
		gender: "unisex",
		promo: "FLAT 60% OFF",
		desc: "Live in Comfort",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Oversized T-shirts",
		image: "/assets/big-saving-zone/big-saving-zone-five.png",
		gender: "unisex",
		promo: "FLAT 60% OFF",
		desc: "Street Style Icon",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Shirts",
		image: "/assets/men/t-shirts.png",
		gender: "men",
		price: 100,
		category: "shirts",
		rating: 4,
		sizes: ["XS", "S", "M", "L", "XL"],
	},
	{
		id: uuidv4(),
		name: "Printed T-shirts",
		image: "/assets/men/printed.png",
		gender: "men",
		price: 100,
		category: "printed-tees",
		rating: 4.5,
	},
	{
		id: uuidv4(),
		name: "Plain T-Shirts",
		image: "/assets/men/plain.png",
		gender: "men",
		price: 100,
		category: "plain-tees",
		rating: 3,
		sizes: ["XS", "S", "M", "L"],

		productDesc:
			"Premium combed cotton blend. Breathable fabric ideal for warm climates. Modern straight cut. Resistant to shrinking. Vibrant prints made using eco-friendly inks.",
		userComments: [{ id: uuidv4(), comment: "Super soft and fits perfectly!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this machine washable?",
				answer: "Yes, it's safe for both machine and hand wash.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Combed Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Graphic" },
			{ id: uuidv4(), label: "Fit", info: "Slim-fit" },
			{ id: uuidv4(), label: "Neck", info: "V-Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Short-sleeves" },
			{ id: uuidv4(), label: "Style", info: "Urban Casual" },
		],
	},

	{
		id: uuidv4(),
		name: "Polo T-shirts",
		image: "/assets/men/polo.png",
		gender: "men",
		price: 100,
		category: "polo",
		rating: 3.5,
		sizes: ["XS", "S", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"100% Bio-washed Cotton – makes the fabric extra soft & silky. Flexible ribbed crew neck. Precisely stitched with no pilling & no fading. Provide  all-time comfort. Anytime, anywhere. Infinite range of matte-finish HD prints.",
		userComments: [{ id: uuidv4(), comment: "" }],
		questionAndAnswer: [{ id: uuidv4(), question: "", answer: "" }],
		extra: [
			{
				id: uuidv4(),
				label: "Fabric",
				info: "Bio-washed Cotton",
			},
			{
				id: uuidv4(),
				label: "Pattern",
				info: "Printed",
			},
			{
				id: uuidv4(),
				label: "Fit",
				info: "Regular-fit",
			},
			{
				id: uuidv4(),
				label: "Neck",
				info: "Rounde Neck",
			},
			{
				id: uuidv4(),
				label: "Steeve",
				info: "Half-sleeves",
			},
			{
				id: uuidv4(),
				label: "Style",
				info: "Bio-washed Cotton",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Hoodies & Sweatshirt",
		image: "/assets/men/hoodies-and-sweatshirt.png",
		gender: "men",
		price: 100,
		category: "hoodies",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Lightweight linen blend perfect for summer wear. Breathable and airy. Designed with a relaxed silhouette. Minimalistic prints for a classy look.",
		userComments: [{ id: uuidv4(), comment: "Great for beach vacations!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Does it wrinkle easily?",
				answer: "A little, as it's a natural linen blend. Ironing recommended.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Linen Blend" },
			{ id: uuidv4(), label: "Pattern", info: "Minimal Print" },
			{ id: uuidv4(), label: "Fit", info: "Relaxed-fit" },
			{ id: uuidv4(), label: "Neck", info: "Mandarin Collar" },
			{ id: uuidv4(), label: "Sleeve", info: "3/4th sleeves" },
			{ id: uuidv4(), label: "Style", info: "Smart Casual" },
		],
	},
	{
		id: uuidv4(),
		name: "Jeans",
		image: "/assets/men/jeans.png",
		gender: "men",
		price: 100,
		category: "jeans",
		rating: 3,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Heavyweight cotton with a fleece lining for warmth. Durable stitching and pre-shrunk. Designed for winter layering. Bold matte-finish graphics.",
		userComments: [{ id: uuidv4(), comment: "Very warm. Wore it all through last winter." }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is the inside brushed or smooth?",
				answer: "It has a brushed fleece inner lining.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Heavy Cotton Fleece" },
			{ id: uuidv4(), label: "Pattern", info: "Solid with print" },
			{ id: uuidv4(), label: "Fit", info: "Oversized" },
			{ id: uuidv4(), label: "Neck", info: "Crew Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Full-sleeves" },
			{ id: uuidv4(), label: "Style", info: "Streetwear" },
		],
	},
	{
		id: uuidv4(),
		name: "Activewear",
		image: "/assets/men/activewear.png",
		gender: "men",
		price: 100,
		category: "activewear",
		rating: 4,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Boxers",
		image: "/assets/men/boxers.png",
		gender: "men",
		price: 100,
		category: "boxers",
		rating: 5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Hoodies & Sweatshirt",
		image: "/assets/women/hoodies-and-sweatshirt.png",
		gender: "women",
		price: 123,
		category: "hoodies",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
	},
	{
		id: uuidv4(),
		name: "Coats & Jackets",
		image: "/assets/women/coats-and-parkas.png",
		gender: "women",
		price: 123,
		category: "coats",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
	},

	{
		id: uuidv4(),
		name: "Blue Flower Print Crop",
		image: "/assets/women/tees-and-t-shirt.png",
		gender: "women",
		brand: "Mellon's Brand",
		price: 123,
		category: "tees",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
	},
	{
		id: uuidv4(),
		name: "White T-shirts",
		image: "/assets/women/boxers.png",
		gender: "women",
		brand: "Helen's Brand",
		price: 123,
		category: "boxers",
		rating: 2.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
	},
	{
		id: uuidv4(),
		name: "Black Sweatshirt",
		image: "/assets/women/black-sweatshirt.png",
		gender: "women",
		price: 123,
		brand: "Jhanvi's Brand",
		rating: 4.5,
		sizes: ["XS", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Line Pattern Black",
		image: "/assets/women/line-pattern-black.png",
		gender: "women",
		price: 123,
		brand: "AS's Brand",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Black Shorts",
		image: "/assets/women/black-short.png",
		gender: "women",
		price: 123,
		brand: "MM's Brand",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Organic bamboo cotton. Naturally antimicrobial and odor-resistant. Ultra-lightweight and sustainable. Designed for active movement.",
		userComments: [{ id: uuidv4(), comment: "Best workout shirt I’ve ever worn!" }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Is this good for running?",
				answer: "Absolutely. It's moisture-wicking and breathable, perfect for workouts.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Bamboo Cotton" },
			{ id: uuidv4(), label: "Pattern", info: "Plain" },
			{ id: uuidv4(), label: "Fit", info: "Athletic-fit" },
			{ id: uuidv4(), label: "Neck", info: "Scoop Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Sleeveless" },
			{ id: uuidv4(), label: "Style", info: "Performance Wear" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Levender Hoodie",
		image: "/assets/women/levender-hoodie.png",
		gender: "women",
		price: 123,
		brand: "Nike's Brand",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		productDesc:
			"Soft-touch polyester with wrinkle resistance. Travel-friendly and easy to maintain. Unisex design with minimal logo embroidery.",
		userComments: [{ id: uuidv4(), comment: "Didn’t crease even after hours of wear." }],
		questionAndAnswer: [
			{
				id: uuidv4(),
				question: "Can I iron this?",
				answer: "You usually won’t need to, but yes—use low heat if you must.",
			},
		],
		extra: [
			{ id: uuidv4(), label: "Fabric", info: "Soft Polyester" },
			{ id: uuidv4(), label: "Pattern", info: "Solid" },
			{ id: uuidv4(), label: "Fit", info: "Unisex" },
			{ id: uuidv4(), label: "Neck", info: "Boat Neck" },
			{ id: uuidv4(), label: "Sleeve", info: "Cap sleeves" },
			{ id: uuidv4(), label: "Style", info: "Everyday Utility" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
];
