import { v4 as uuidv4 } from "uuid";
import { AllProductsType } from "@/app/types";

export const allProducts: AllProductsType[] = [
	{
		id: uuidv4(),
		name: "Knitted Joggers",
		image: "/assets/new-arrival/new-arrival-one.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Full Sleeve",
		image: "/assets/new-arrival/new-arrival-two.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Active T-Shirts",
		image: "/assets/new-arrival/new-arrival-three.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Urban Shirts",
		image: "/assets/new-arrival/new-arrival-four.png",
		gender: "unisex",
		tags: [{ section: "NewArrival", type: "curated" }],
	},
	{
		id: uuidv4(),
		name: "Hawaiian Shirts",
		image: "/assets/big-saving-zone/big-saving-zone-one.png",
		gender: "unisex",
		promo: "UP TO 50% OFF",
		desc: "Dress up in summer vibe",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Printed T-Shirts",
		image: "assets/big-saving-zone/big-saving-zone-two.png",
		gender: "unisex",
		promo: "UP TO 40% OFF",
		desc: "New Designs Every Week",
		custom: "limited",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Cargo Joggers",
		image: "/assets/big-saving-zone/big-saving-zone-three.png",
		gender: "unisex",
		promo: "UP TO 50% OFF",
		desc: "Move with style & comfort",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Urban Shirts",
		image: "/assets/big-saving-zone/big-saving-zone-four.png",
		gender: "unisex",
		promo: "FLAT 60% OFF",
		desc: "Live in Comfort",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Oversized T-shirts",
		image: "/assets/big-saving-zone/big-saving-zone-five.png",
		gender: "unisex",
		promo: "FLAT 60% OFF",
		desc: "Street Style Icon",
		tags: [
			{
				section: "BigSavingZone",
				type: "promotional",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Shirts",
		image: "/assets/men/t-shirts.png",
		gender: "men",
		price: 100,
		category: "shirts",
		rating: 4,
		sizes: ["XS", "S", "M", "L", "XL"],
	},
	{
		id: uuidv4(),
		name: "Printed T-shirts",
		image: "/assets/men/printed.png",
		gender: "men",
		price: 100,
		category: "printed-tees",
		rating: 4.5,
	},
	{
		id: uuidv4(),
		name: "Plain T-Shirts",
		image: "/assets/men/plain.png",
		gender: "men",
		price: 100,
		category: "plain-tees",
		rating: 3,
		sizes: ["XS", "S", "M", "L"],
	},
	{
		id: uuidv4(),
		name: "Polo T-shirts",
		image: "/assets/men/polo.png",
		gender: "men",
		price: 100,
		category: "polo",
		rating: 3.5,
		sizes: ["XS", "S", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Hoodies & Sweatshirt",
		image: "/assets/men/hoodies-and-sweatshirt.png",
		gender: "men",
		price: 100,
		category: "hoodies",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Jeans",
		image: "/assets/men/jeans.png",
		gender: "men",
		price: 100,
		category: "jeans",
		rating: 3,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Activewear",
		image: "/assets/men/activewear.png",
		gender: "men",
		price: 100,
		category: "activewear",
		rating: 4,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Boxers",
		image: "/assets/men/boxers.png",
		gender: "men",
		price: 100,
		category: "boxers",
		rating: 5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Hoodies & Sweatshirt",
		image: "/assets/women/hoodies-and-sweatshirt.png",
		gender: "women",
		price: 123,
		category: "hoodies",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Coats & Jackets",
		image: "/assets/women/coats-and-parkas.png",
		gender: "women",
		price: 123,
		category: "coats",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},

	{
		id: uuidv4(),
		name: "Blue Flower Print Crop",
		image: "/assets/women/tees-and-t-shirt.png",
		gender: "women",
		brand: "Mellon's Brand",
		price: 123,
		category: "tees",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "White T-shirts",
		image: "/assets/women/boxers.png",
		gender: "women",
		brand: "Helen's Brand",
		price: 123,
		category: "boxers",
		rating: 2.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
	},
	{
		id: uuidv4(),
		name: "Black Sweatshirt",
		image: "/assets/women/black-sweatshirt.png",
		gender: "women",
		price: 123,
		brand: "Jhanvi's Brand",
		rating: 4.5,
		sizes: ["XS", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Line Pattern Black",
		image: "/assets/women/line-pattern-black.png",
		gender: "women",
		price: 123,
		brand: "AS's Brand",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Black Shorts",
		image: "/assets/women/black-short.png",
		gender: "women",
		price: 123,
		brand: "MM's Brand",
		rating: 4.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
	{
		id: uuidv4(),
		name: "Levender Hoodie",
		image: "/assets/women/levender-hoodie.png",
		gender: "women",
		price: 123,
		brand: "Nike's Brand",
		rating: 3.5,
		sizes: ["XS", "S", "M", "L", "XL"],
		colors: [
			{ name: "black", colorCode: "bg-[#3C4242]" },
			{ name: "yellow", colorCode: "bg-[#EDD146]" },
			{ name: "pink", colorCode: "bg-[#EB84B0]" },
			{ name: "red-brown", colorCode: "bg-[#9C1F35]" },
		],
		tags: [
			{
				section: "InTheLimelight",
				type: "curated",
			},
		],
	},
];
